Первое задание
SRTsila/Robots pull request #1
Opened 2020-05-06 12:10 UTC by SRTsila

2020-05-16 10:58 UTC, shaykemelov requested changes
tofix

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/GameWindow.java
лишняя пустая строка

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/LogWindow.java
>      private TextArea m_logContent;
поля могут быть `final`

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
>      private final JDesktopPane desktopPane = new JDesktopPane();
предлагаю вынести инициализацию поля в конструктор для единообразия с остальными полями класса

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    private GameWindow gameWindow;
поля могут быть `final`

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    protected LogWindow createLogWindow() {
метод может быть `private`

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    protected void addWindow(JInternalFrame frame) {
метод может быть `private`

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
>  //    protected JMenuBar createMenuBar() {
закомментированный код

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    private JMenu createSubMenu(String name, String[] subMenuNames, int key) {
1. метод может быть `static`
2. предлагаю изменить порядок аргументов и сделать `subMenuNames` vararg
`private static JMenu createSubMenu(String name, int key, String... subMenuNames)`
таким образом при вызове методе не нужно будет руками создавать массив
```
JMenu lookAndFeelMenu = createSubMenu(
                "Режим отображения",
                KeyEvent.VK_V,
                "Управление режимом отображения приложения"
);
```

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
>          {
лишнии блоки не нужны. всё идет к тому, чтобы создать отдельные методы для каждого элемента меню

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/RobotsProgram.java
>  //        UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
закоментированный код - его быть не должно, он не делает ничего полезного, мешает и занимает место

2020-05-16 10:58 UTC, shaykemelov commented on robots/src/gui/RobotsProgram.java
> +            });
предлагаю вынести это в отдельный класс. можно сделать его вложенным статическим
```
    private static class WindowClosingAdapter extends WindowAdapter {
        @Override
        public void windowClosing(final WindowEvent e)
        {
            Object[] options = {"Yes", "No"};
            int code = JOptionPane.showOptionDialog(e.getWindow(),
                    "Close app?", "Confirm",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, options, options[0]);
            if (code == 0) {
                e.getWindow().setVisible(false);
                System.exit(0);
            }
        }
    }
```

и после это будет выглядить вот так

```
SwingUtilities.invokeLater(() -> {
            MainApplicationFrame frame = new MainApplicationFrame();
            frame.pack();
            frame.setVisible(true);
            frame.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
            frame.addWindowListener(new WindowClosingAdapter());
            frame.setExtendedState(Frame.MAXIMIZED_BOTH);
        });
```
так будет легче читать код и будущем легче поддерживать

2020-05-21 09:09 UTC, SRTsila commented
@shaykemelov 
Всё поправил

2020-05-23 15:39 UTC, shaykemelov approved these changes
lgtm, лишнюю строку убери в следующей задаче

2020-05-23 15:39 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +            exitItem.add(new JButton());
это лишнее

2020-05-23 15:40 UTC, merged